dappAddress: '<dappAddress>'

gameapi: 
  url: '<game-API-URL>'
  timetosleepinseconds: 30
  elapsedtimebetweenchecksinseconds: 900

gamemaster:
  blocksperround: 2
  nodeurl: 'https://nodes-testnet.wavesnodes.com'
  chainid: 'T'
  chain: 'Testnet'
  signingcertificate: "-----BEGIN RSA PRIVATE KEY-----\n<privatekey>\n-----END RSA PRIVATE KEY-----"
  seed: '<seed>'

logging:
  level: 'DEBUG'
  format: "%(asctime)s %(levelname)s %(threadName)-10s %(message)s"