dappAddress: '<dappAddress>'

gamemaster:
  gamesToPrepare: 1
  nodeurl: 'https://nodes-testnet.wavesnodes.com'
  chainid: 'T'
  chain: 'Testnet'
  signingcertificate: "-----BEGIN RSA PRIVATE KEY-----\n<privatekey>\n-----END RSA PRIVATE KEY-----"
  seed: '<seed>'
  encryptionKey: '<encryptionKey>'

logging:
  level: 'DEBUG'
  format: "%(asctime)s %(levelname)s %(threadName)-10s %(message)s"